mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import index

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('seoilNotice/', include('seoilNotice.urls')),
    path('libNotice/', include('seoilLibraryNotice.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/seoilLibraryNotice/urls.py
from django.urls import path
from seoilLibraryNotice.views import LibNoticeListView, NewsInfoListView

app_name = 'seoilLibraryNotice'
urlpatterns = [
    path('notice', LibNoticeListView.as_view(), name='notice'),
    path('news', NewsInfoListView.as_view(), name='event'),
]

mysite/seoilNotice/urls.py
from django.urls import path

from seoilNotice import views
from seoilNotice.views import NoticeListView, EventInfoListView, BachelorNoticeListView

app_name = 'seoilNotice'
urlpatterns = [
    path('notice', NoticeListView.as_view(), name='notice'),
    path('event', EventInfoListView.as_view(), name='event'),
    path('bachelor', BachelorNoticeListView.as_view(), name='bachelor'),
    path('search/', views.SearchFormView.as_view(), name='search'),
]

mysite/seoilLibraryNotice/models.py
from django.db import models

class LibNotice(models.Model):
    title = models.CharField(max_length=200)
    date = models.CharField(max_length=20)
    url = models.URLField()

    def __str__(self):
        return self.title

class NewsInfo(models.Model):
    title = models.CharField(max_length=200)
    date = models.CharField(max_length=20)
    url = models.URLField()

    def __str__(self):
        return self.title

mysite/seoilNotice/models.py
from django.conf import settings
from django.db import models

class SeoilNotice(models.Model):
    title = models.CharField(max_length=200)
    date = models.CharField(max_length=20)
    url = models.URLField()

    def __str__(self):
        return self.title

class EventInfo(models.Model):
    title = models.CharField(max_length=200)
    date = models.CharField(max_length=20)
    url = models.URLField()

    def __str__(self):
        return self.title

class BachelorNotice(models.Model):
    title = models.CharField(max_length=200)
    date = models.CharField(max_length=20)
    url = models.URLField()

    def __str__(self):
        return self.title

mysite/seoilNotice/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

mysite/mysite/views.py
from django.http import HttpResponse
from django.template import loader
from seoilNotice.views import SeoilNotice, EventInfo, BachelorNotice
from seoilLibraryNotice.views import NewsInfo, LibNotice

#https://oneone-note.tistory.com/36
def index(request):
    latest_post_list = SeoilNotice.objects.all().order_by('id')[:5]
    latest_event_list = EventInfo.objects.all().order_by('id')[:5]
    latest_bachelor_list = BachelorNotice.objects.all().order_by('id')[:5]
    latest_libnews_list = LibNotice.objects.all().order_by('id')[:5]
    latest_libnotice_list = NewsInfo.objects.all().order_by('id')[:5]

    template = loader.get_template('home.html')
    context = {
        'latest_post_list': latest_post_list,
        'latest_event_list': latest_event_list,
        'latest_bachelor_list': latest_bachelor_list,
        'latest_libnews_list': latest_libnews_list,
        'latest_libnotice_list': latest_libnotice_list,
    }
    return HttpResponse(template.render(context, request))

mysite/seoilLibraryNotice/views.py
from django.views.generic import ListView
from seoilLibraryNotice.models import LibNotice, NewsInfo


class LibNoticeListView(ListView):
    model = LibNotice
    context_object_name = 'lib_notices'


class NewsInfoListView(ListView):
    model = NewsInfo
    context_object_name = 'news'

mysite/seoilNotice/views.py
from django.views.generic import ListView, FormView
from seoilNotice.models import SeoilNotice, EventInfo, BachelorNotice
from seoilNotice.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render


class NoticeListView(ListView):
    model = SeoilNotice
    context_object_name = 'notices'


class EventInfoListView(ListView):
    model = EventInfo
    context_object_name = 'events'


class BachelorNoticeListView(ListView):
    model = BachelorNotice
    context_object_name = 'bachelor'


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'seoilNotice/search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = SeoilNotice.objects.filter(Q(title__icontains=searchWord) |
                                               Q(date__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)

mysite/mysite/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Django Web Programming{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% block extra-style %}{% endblock %}
</head>
<body style="padding-top:90px;">


<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <a class="navbar-brand" href="{% url 'home' %}" style="margin-right:150px;"><b>서일공지알림이</b></a>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          서일공지
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'seoilNotice:event' %}">행사안내</a>
          <a class="dropdown-item" href="{% url 'seoilNotice:notice' %}">공지사항</a>
          <a class="dropdown-item" href="{% url 'seoilNotice:bachelor' %}">학사공지</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          세방공지
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'seoilLibraryNotice:notice' %}">공지사항</a>
          <a class="dropdown-item" href="{% url 'seoilLibraryNotice:event'%}">NEWS</a>
        </div>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          검색창
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'seoilNotice:search' %}">서일공지</a>
        </div>
      </li>
    </ul>
  </div>

</nav>

<div class="container">
{% block content %}

{% endblock content%}
</div>
<hr class="featurette-divider">
<footer class="container">
  <p>Bootstrap과 Django를 사용하였습니다.</p>
  <p>문의사항은 hesoo98@naver.com로 부탁드립니다.</p>
  <p class="float-right"><a href="#">맨 위로</a> </p>

</footer>


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}
</body>
</html>

mysite/mysite/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Home Page{% endblock %}

{% block extra-style %}
<style>
ul {
    list-style:none;
    padding-left:0px;
}
li {
    font-size:20px;
}
.box {
    margin-bottom:30px;
}
.up_bar {
    text-align: center;
    margin-bottom:30px;
    position:relative;
}
.up_bar{
    position: relative;
}

.text {
    position: absolute;
    top : 50%;
    left: 50%;
    transform: translate( -50%, -50% );
}
</style>

{% endblock %}

{% block content %}
<div class="up_bar">
    <img src="/static/mysite/images/home_image01.png" alt="이미지" class="">
    <div class="text"><p style="color:white;font-size:50px;"><b>서일 공지사항 알림이</b></p></div>
</div>



<div class="container">
    <div>
        <h4>서일공지-행사안내</h4>
        <ul class="list-group box">
            {% for notice in latest_event_list %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
               <a href="{{ notice.url }}" target="_blank">{{ notice.title }}</a>
                <span class="badge badge-primary badge-pill">{{ notice.date }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div>
        <h4>서일공지-공지사항</h4>
        <ul class="list-group box">
            {% for notice in latest_post_list %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
               <a href="{{ notice.url }}" target="_blank">{{ notice.title }}</a>
                <span class="badge badge-primary badge-pill">{{ notice.date }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div>
        <h4>서일공지-학사공지</h4>
        <ul class="list-group box">
            {% for notice in latest_bachelor_list %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
               <a href="{{ notice.url }}" target="_blank">{{ notice.title }}</a>
                <span class="badge badge-primary badge-pill">{{ notice.date }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div>
        <h4>세방공지-공지사항</h4>
        <ul class="list-group box">
            {% for notice in latest_libnotice_list %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
               <a href="{{ notice.url }}" target="_blank">{{ notice.title }}</a>
                <span class="badge badge-primary badge-pill">{{ notice.date }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>

    <div>
        <h4>세방공지-NEWS</h4>
        <ul class="list-group box">
            {% for notice in latest_libnews_list %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
               <a href="{{ notice.url }}" target="_blank">{{ notice.title }}</a>
                <span class="badge badge-primary badge-pill">{{ notice.date }}</span>
            </li>
            {% endfor %}
        </ul>
    </div>

</div>

{% endblock content %}

mysite/seoilLibraryNotice/templates/seoilLibraryNotice/libnotice_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}libnotice_list.html{% endblock %}

{% block extra-style %}
<style>
ul {
    list-style:none;
    padding-left:0px;
}
li {
    font-size:20px;
}
</style>

{% endblock %}

{% block content %}

<div class="container">
  <h4>세방도서관-공지사항</h4>
  {% for notice in lib_notices %}
    <div>
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <a href='{{ notice.url }}' target="_blank">{{ notice.title }}</a>
          <span class="badge badge-primary badge-pill">{{ notice.date }}</span>
        </li>
      </ul>
    </div>
    {% endfor %}
</div>
{% endblock content%}

mysite/seoilLibraryNotice/templates/seoilLibraryNotice/newsinfo_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}newsinfo_list.html{% endblock %}

{% block extra-style %}
<style>
ul {
    list-style:none;
    padding-left:0px;
}
li {
    font-size:20px;
}
</style>

{% endblock %}

{% block content %}

<div class="container">
  <h4>세방도서관-NEWS</h4>
  {% for notice in news %}
    <div>
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <a href='{{ notice.url }}' target="_blank">{{ notice.title }}</a>
          <span class="badge badge-primary badge-pill">{{ notice.date }}</span>
        </li>
      </ul>
    </div>
    {% endfor %}
</div>
{% endblock content%}

mysite/seoilNotice/templates/seoilNotice/bachelornotice_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}eventinfo_list.html{% endblock %}

{% block extra-style %}
<style>
ul {
    list-style:none;
    padding-left:0px;
}
li {
    font-size:20px;
}
</style>

{% endblock %}

{% block content %}

<div class="container">
  <h4>서일공지-학사공지</h4>
  {% for notice in bachelor %}
    <div>
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <a href='{{ notice.url }}' target="_blank">{{ notice.title }}</a>
          <span class="badge badge-primary badge-pill">{{notice.date}}</span>
        </li>
      </ul>
    </div>
    {% endfor %}
</div>
{% endblock content%}

mysite/seoilNotice/templates/seoilNotice/eventinfo_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}eventinfo_list.html{% endblock %}

{% block extra-style %}
<style>
ul {
    list-style:none;
    padding-left:0px;
}
li {
    font-size:20px;
}
</style>

{% endblock %}

{% block content %}

<div class="container">
  <h4>서일공지-행사안내</h4>
  {% for notice in events %}
    <div>
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <a href='{{ notice.url }}' target="_blank">{{ notice.title }}</a>
          <span class="badge badge-primary badge-pill">{{ notice.date }}</span>
        </li>
      </ul>
    </div>
    {% endfor %}
</div>
{% endblock content%}

mysite/seoilNotice/templates/seoilNotice/search.html
{% extends "base.html" %}

{% block title %}search.html{% endblock %}

{% block content %}
<form action="." method="post">{% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
</form>
<br><br>

{% if object_list %}
{% for post in object_list %}
    <h2><a href="{{ post.get_absolute_url}}">{{ post.title }}</a> </h2>
    <p>{{ post.date }}</p>
{% endfor %}

{% elif search_term %}
 <b><i>Search Word({{ search_term }}) Not Found</i></b>
{% endif %}
{% endblock %}

mysite/seoilNotice/templates/seoilNotice/seoilnotice_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}seoilnotice_list.html{% endblock %}

{% block extra-style %}
<style>
ul {
    list-style:none;
    padding-left:0px;
}
li {
    font-size:20px;
}
</style>

{% endblock %}

{% block content %}
<div class="container">
  <h4>서일공지-공지사항</h4>
  {% for notice in notices %}
    <div>
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <a href='{{ notice.url }}' target="_blank">{{ notice.title }}</a>
          <span class="badge badge-primary badge-pill">{{ notice.date }}</span>
        </li>
      </ul>
    </div>
    {% endfor %}
</div>
{% endblock content%}